openapi: 3.0.1
info:
  title: Item Management Service
  description: This is a simple API for managing items.
  version: 1.0.0
servers:
- url: http://localhost:8080/api
tags:
- name: item
  description: Everything about your Items
paths:
  /items:
    get:
      tags:
      - item
      summary: List all items
      description: Returns a list of items
      operationId: itemsGET
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
                x-content-type: application/json
      x-swagger-router-controller: Item
    post:
      tags:
      - item
      summary: Create a new item
      description: Creates a new item
      operationId: itemsPOST
      requestBody:
        description: Item object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        "201":
          description: Item created
          content: {}
      x-codegen-request-body-name: body
      x-swagger-router-controller: Item
  /items/{itemId}:
    get:
      tags:
      - item
      summary: Find item by ID
      description: Returns a single item
      operationId: itemsItemIdGET
      parameters:
      - name: itemId
        in: path
        description: ID of item to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        "404":
          description: Item not found
          content: {}
      x-swagger-router-controller: Item
    put:
      tags:
      - item
      summary: Update an existing item
      description: Updates an existing item
      operationId: itemsItemIdPUT
      parameters:
      - name: itemId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Updated item object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        "200":
          description: Item updated
          content: {}
        "404":
          description: Item not found
          content: {}
      x-codegen-request-body-name: body
      x-swagger-router-controller: Item
    delete:
      tags:
      - item
      summary: Delete an item
      description: Deletes an item
      operationId: itemsItemIdDELETE
      parameters:
      - name: itemId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Item deleted
          content: {}
        "404":
          description: Item not found
          content: {}
      x-swagger-router-controller: Item
components:
  schemas:
    Item:
      required:
      - name
      - price
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: float
      example:
        price: 6.0274563
        name: name
        id: 0
x-original-swagger-version: "2.0"
